### Default route
GET http://localhost:3000

### Protected route
GET http://localhost:3000
Authorization: Bearer <accessToken>

### Route to test the error not found
GET http://localhost:3000/health

### Route to test auth/register
POST  http://localhost:3000/auth/register
# Header
Content-Type: application/json
# Body
{
    "email": "user@mail.com",
    "password": "verysecured",
    "name" : "Hello world",
    "phoneNo": "03212518089"
}

### Route to test auth/login
POST  http://localhost:3000/auth/login
# Header
Content-Type: application/json
# Body
{
    "email": "user4@mail.com",
    "password": "verysecured"
}

### Route to test auth/refresh_token
POST  http://localhost:3000/auth/refresh_token
# Header
Content-Type: application/json

# Body
{
    "refresh_token": "<refreshToken>"
}

### Route to test user/getAll
GET http://localhost:3000/user/getAll
# Header
Authorization: Bearer <accessToken>

### Route to test user/getAll
GET http://localhost:3000/user?id=63611dfac12eaf8eb3704245
# Header
Authorization: Bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjcyOTYwNzEsImV4cCI6MTY2NzI5Njk3MSwiYXVkIjoiNjM2MGU1NzAzY2ZjOWU0NzI4ZmM2YzU5IiwiaXNzIjoiQmFzaWNBUEkgRGVtbyBUZWFtIn0.Va8asYzetnBv0wuHX9m8cThs0YP8W55WU--O_uGz6E0

### Route to test user/id
GET http://localhost:3000/user/6360e5703cfc9e4728fc6c59
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NjczMTAzODgsImV4cCI6MTY2NzMxMzk4OCwiYXVkIjoiNjM2MTFkZmFjMTJlYWY4ZWIzNzA0MjQ1IiwiaXNzIjoiQmFzaWNBUEkgRGVtbyBUZWFtIn0.Tiz0z33Y0RTyG-25IJsJVu9exmkBgr1h4kkVlhcmDiA

### Route to test auth/logout
DELETE   http://localhost:3000/auth/logout